version: 2

jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm i -g npm

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm ci
      - run: npm run lerna bootstrap

      - run: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
