version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    NODE_ENV: production
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "package-lock.json" }}
          - deps-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package-lock.json" }}

      - run: npm run lerna bootstrap

      - run: npm test

      - persist_to_workspace:
          paths:
            - ./

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./

      - run: npm run lerna publish -- --yes --conventional-commits

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
